spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=postgres
spring.datasource.password=@9368Aadya
jwt.secret=your-very-long-random-secret-key-here
jwt.expiration=3600000